version: '3.5'
services:
    api:
        build:
            context: ./api
            args:
                - REPO_URL=${REPO_URL}
                - REPO_BRANCH=${REPO_BRANCH}
                - REPO_USER=${REPO_USER}
                - REPO_PWD=${REPO_PWD}
                - WORKDIR=${WORKDIR}
    web:
        build:
            context: ./web
            args:
                - WORKDIR=${WORKDIR}